const location = {
  // 桃園市各區
  68000: "桃園市",
  Taoyuan: "桃園區",
  Zhongli: "中壢區",
  Daxi: "大溪區",
  Yangmei: "楊梅區",
  68000050: "蘆竹區",
  68000060: "大園區",
  Guishan: "龜山區",
  Bade: "八德區",
  Longtan: "龍潭區",
  68000100: "平鎮區",
  Xinwu: "新屋區",
  Guanyin: "觀音區",
  Fuxing: "復興區",

  // 蘆竹區詳細區域（里）
  Shanqiao: "山腳里",
  Nanxing: "南興里",
  Beishi: "北勢里",
  Nankan: "南崁里",
  Chengan: "長安里",
  Luming: "蘆竹里",
  Jianguo: "建國里",
  Nanqiao: "南橋里",
  Zhenxing: "振興里",
  Wende: "文德里",
  Xinnan: "新南里",
  Shanjiao: "山腳里",
  68000050040: "濱海里",

  // 大園區
  Dayuan: "大園里",
  Daxing: "大興里",
  Tianxin: "田心里",
  Houcuo: "后厝里",
  Xihai: "溪海里",
  Wuchuan: "五權里",
  Hengfeng: "橫峰里",
  Qingshan: "青山里",
  Qingfeng: "青峰里",
  Heping: "和平里",
  Neihai: "內海里",
  Nangang: "南港里",
  Zhentou: "圳頭里",
  Puxin: "埔心里",
  68000060012: "竹圍里",
  Beigang: "北港里",
  Shalun: "沙崙里",
  Sanshi: "三石里",
  Gualin: "菓林里",
  Haikou: "海口里",

  // 桃園區詳細區域（里）
  Chenggong: "成功里",
  Zhongshan: "中山里",
  Fuyuan: "福源里",
  Guanghua: "光華里",
  Nanshan: "南山里",

  // 中壢區詳細區域（里）
  Xinming: "新明里",
  Pingan: "平安里",
  Daxin: "大新里",
  Sanyuan: "三元里",

  // 八德區詳細區域（里）
  Dazhu: "大竹里",
  Fuxing: "復興里",
  Xinyi: "信義里",

  // 龜山區詳細區域（里）
  Daxing: "大興里",
  Nanyuan: "南園里",
  Wenhua: "文化里",

  // 觀音區詳細區域（里）
  Dalin: "大林里",
  Longtan: "龍潭里",

  // 新北市各區
  65000: "新北市",
  Banqiao: "板橋區",
  Sanchong: "三重區",
  Zhonghe: "中和區",
  Yonghe: "永和區",
  Xinzhuang: "新莊區",
  Xindian: "新店區",
  Tucheng: "土城區",
  Luzhou: "蘆洲區",
  Wugu: "五股區",
  Taishan: "泰山區",
  Shulin: "樹林區",
  Yingge: "鶯歌區",
  Sanxia: "三峽區",
  Danshui: "淡水區",
  Bali: "八里區",
  Xizhi: "汐止區",
  Jinshan: "金山區",
  Wanli: "萬里區",
  Shimen: "石門區",
  Ruifang: "瑞芳區",
  Pingxi: "平溪區",
  Shuangxi: "雙溪區",
  Gongliao: "貢寮區",
  Wulai: "烏來區",

  // 板橋區詳細區域（里）
  Guoqiang: "國強里",
  Guanghua: "光華里",
  Zhongxing: "中興里",
  Fuzhong: "府中里",

  // 新莊區詳細區域（里）
  Hougang: "後港里",
  Fuhe: "福和里",
  Xinyi: "信義里",
  Zhongxin: "中信里",

  // 三重區詳細區域（里）
  Baoshun: "保順里",
  Baofu: "保福里",
  Qiaozhong: "橋中里",
  Chengtai: "成功里",

  // 中和區詳細區域（里）
  Yongxing: "永興里",
  Jingxin: "景新里",
  Fuxing: "復興里",
  Nanshan: "南山里",

  // 永和區詳細區域（里）
  Renai: "仁愛里",
  Zhongshan: "中山里",
  Yongping: "永平里",
  Baoan: "保安里",

  // 淡水區詳細區域（里）
  Shalun: "沙崙里",
  Zhongzheng: "中正里",
  Beishan: "北山里",
  Qingzhi: "青芝里",

  // 汐止區詳細區域（里）
  Xizhi: "汐止里",
  Xinyi: "信義里",
  Dingxi: "頂溪里",
  Xiushan: "秀山里",

  // 瑞芳區詳細區域（里）
  Shenmei: "深美里",
  Qitang: "七堵里",
  Longmen: "龍門里",
  Nanyang: "南洋里",

  // 台北市各區
  63000: "台北市",
  Songshan: "松山區",
  Xinyi: "信義區",
  Daan: "大安區",
  Zhongshan: "中山區",
  Zhongzheng: "中正區",
  Datong: "大同區",
  Wanhua: "萬華區",
  Nangang: "南港區",
  Neihu: "內湖區",
  Shilin: "士林區",
  Beitou: "北投區",

  // 松山區詳細區域（里）
  Fuxing: "復興里",
  Changchun: "長春里",
  Mingcheng: "民權里",
  Minsheng: "民生里",

  // 信義區詳細區域（里）
  Yongji: "永吉里",
  Songde: "松德里",
  Xinyi: "信義里",
  Yongchun: "永春里",

  // 大安區詳細區域（里）
  Renai: "仁愛里",
  Heping: "和平里",
  Jinhua: "金華里",
  Fuxing: "復興里",

  // 中山區詳細區域（里）
  Zhongshan: "中山里",
  Minquan: "民權里",
  Songjiang: "松江里",
  Jilin: "吉林里",

  // 中正區詳細區域（里）
  Guling: "古亭里",
  Nanchang: "南昌里",
  Jinshan: "金山里",
  Shida: "師大里",

  // 大同區詳細區域（里）
  Chengde: "承德里",
  Yanping: "延平里",
  Dihua: "迪化里",
  Taiyuan: "太原里",

  // 萬華區詳細區域（里）
  Xichang: "西昌里",
  Longshan: "龍山里",
  Heping: "和平里",
  Zhonghua: "中華里",

  // 南港區詳細區域（里）
  Jingmao: "經貿里",
  Kunyang: "昆陽里",
  Zhongshan: "中山里",
  Nangang: "南港里",

  // 內湖區詳細區域（里）
  Neihu: "內湖里",
  Zhongyi: "忠義里",
  Huzhou: "湖洲里",
  Xihu: "西湖里",

  // 士林區詳細區域（里）
  Tianmu: "天母里",
  Zhishan: "至善里",
  Fushan: "福山里",
  Shilin: "士林里",

  // 北投區詳細區域（里）
  Guandu: "關渡里",
  Qiyan: "奇岩里",
  Xinbeitou: "新北投里",
  Zhongyang: "中央里",

  // 新竹縣
  10004: "新竹縣",
  Zhongxing: "中興里",
  Dongping: "東平里",
  Aikou: "隘口里",
  Dongxing: "東興里",
  Donghai: "東海里",
  Doulun: "斗崙里",
  Xinlun: "新崙里",
  Lucang: "鹿場里",
  Xinzhu: "竹北里",
  Zhren: "竹仁里",
  Zhyi: "竹義里",
  Fude: "福德里",
  Taihe: "泰和里",
  Shixing: "十興里",
  Qianjia: "千甲里",
  Zhongzheng: "中正里",
  Liujia: "六家里",
  Zhuangjing: "莊敬里",
  Jiafeng: "嘉豐里",
  Xinzhuang: "新庄里",
  Keyuan: "科園里",
  Dongyuan: "東園里",
  Gongyuan: "公園里",
  Dongshan: "東山里",
  Jianhua: "建華里",
  Guangfu: "光復里",
  Lushui: "綠水里",
  Shuiyuan: "水源里",
  Qianxi: "前溪里",
  Ziqiang: "自強里",
  Xinxing: "新興里",
  Zhenxing: "振興里",
  Fude2: "福德里",
  Nanshi: "南市里",
  GuanDi: "關帝里",
  Nanmen: "南門里",
  XianGong: "仙宮里",
  Jinshan: "金山里",
  Xianshui: "仙水里",
  Guandong: "關東里",
  Xinzhuang2: "新莊里",
  Keyuan2: "科園里",
  Pudding: "埔頂里",
  Longshan: "龍山里",
  Wugong: "武功里",
  Fenggong: "豐功里",
  Jungong: "軍功里",
  Jiangong: "建功里",
  Ligong: "立功里",
  Guangming: "光明里",
  Zhongzheng2: "中正里",
  Qinren: "親仁里",
  Rongguang: "榮光里",
  Yuxian: "育賢里",
  Chenggong: "成功里",
  Sanmin: "三民里",
  Fuzhong: "復中里",
  Wenhua: "文華里",
  JinHua: "錦華里",

  // 高雄
  64000: "高雄市",
  Yancheng: "鹽埕區",
  Gushan: "鼓山區",
  Zuoying: "左營區",
  Nanzi: "楠梓區",
  Sanmin: "三民區",
  Xinxing: "新興區",
  Qianjin: "前金區",
  Lingya: "苓雅區",
  Qianzhen: "前鎮區",
  Qijin: "旗津區",
  Xiaogang: "小港區",
  Fengshan: "鳳山區",
  Daliao: "大寮區",
  Linyuan: "林園區",
  Niaosong: "鳥松區",
  Dashu: "大樹區",
  Renwu: "仁武區",
  Dashe: "大社區",
  Gangshan: "岡山區",
  Yanchao: "燕巢區",
  Tianliao: "田寮區",
  Alian: "阿蓮區",
  Luzhu: "路竹區",
  Hunei: "湖內區",
  Qiaotou: "橋頭區",
  Ziguan: "梓官區",
  Mituo: "彌陀區",
  Yongan: "永安區",
  Jiading: "茄萣區",
  Qishan: "旗山區",
  Meinong: "美濃區",
  Liugui: "六龜區",
  Neimen: "內門區",
  Shanlin: "杉林區",
  Jiaxian: "甲仙區",
  Taoyuan: "桃源區",
  Maolin: "茂林區",
  Namaxia: "那瑪夏區",

  // 連江縣
  "09007": "連江縣",
};

export default location;
